export const routes = {
  home: "/",
  collections: "/collections",
  kitchens: "/collections/kitchens",
  bedrooms: "/collections/bedrooms",
  outdoor: "/collections/outdoor",
  complements: "/collections/complements",
  products: "/products",
  virtualShowroom: "/virtual-showroom",
  contact: "/contact",
  dashboard: "/dashboard",
  cart: "/cart",
  checkout: "/checkout",
  wishlist: "/wishlist",
  login: "/Login",
  signup: "/Signup",
  adminDashboard: "/admin/dashboard",
  privacy: "/privacy",
  terms: "/terms",
  shipping: "/shipping",
  sustainability: "/sustainability",
};
